money_splitter/urls.py
from django.contrib import admin
from django.urls import path, include
from splitter import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.HomePage, name="home"),
    path('admin123/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('splitter/', include('splitter.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

splitter/urls.py
from django.urls import path
from splitter import views

app_name = 'splitter'

urlpatterns = [
    path('signup/',views.signup,name="signup"),
    path('login/',views.user_login,name="login"),
    path('logout/',views.user_logout,name="logout"),
    path('create_room/',views.add_room,name="add_room"),
    path('rooms_list/',views.room_list,name="room_list"),
    path('rooms_detail/<int:pk>',views.room_details,name="room_detail"),
    path('rooms_detail/<int:pk>/create_transaction',views.create_transaction,name="create_transaction"),
    path('my_debts/',views.my_debts,name="my_debts"),
    # change
    path('paym/',views.paym,name="payment"),
    ## Changed by captain
    path("paynow/", views.paynow,name="paynow"),

    path('settle_debt/<int:pk>',views.delete_debt,name="delete_debt"),
    path('final_settlements/',views.final_settlements,name="final_settlements"),
    path('members_list/<int:pk>/',views.list_members,name="list_members"),
    path('add_members/<int:pk>/add/<int:id>/',views.add_member,name="add_member"),
    path('personal_budget/',views.personal_budget,name="personal_budget"),
    path('add_personal_budget/',views.add_personal_budget,name="add_personal_budget"),
    path('delete_personal_income/<int:pk>/',views.delete_personal_income,name="delete_personal_income"),

    ## Added remainder
    path('remainder/<username>/<amount>', views.send_remainder, name='remainder'),
    path('delete_personal_expense/<int:pk>/',views.delete_personal_expense,name="delete_personal_expense"),
    path('<int:pk>/update_transaction/<int:id>/',views.update_transaction,name="update_transaction"),
    path('transaction_details/<int:pk>/',views.transaction_details,name="transaction_details"),
    path('join_us/',views.joinus,name="joinus"),
    
    ]

splitter/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass

class room(models.Model):
    creater = models.ForeignKey(User,on_delete=models.CASCADE,related_name="creater")
    name = models.CharField(max_length=250)
    members = models.ManyToManyField(User,through="room_members")

    def __str__(self):
        return self.name

class room_members(models.Model):
    room = models.ForeignKey(room, on_delete = models.CASCADE, related_name = "room_name")
    member = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "room_member")

    def __str__(self):
        return self.member.username + ' in group ' + self.room.name

    class Meta:
        unique_together = ('room','member')

class transaction(models.Model):
    room = models.ForeignKey(room, on_delete = models.CASCADE, related_name = 'room_transaction')
    amount = models.IntegerField()
    reason = models.CharField(max_length = 250)
    created_at = models.DateTimeField(auto_now=True)
    payer = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'transaction_payer')
    splitters = models.ManyToManyField(User, related_name = "transaction_members")

    def __str__(self):
        return self.reason + ' in group ' + self.room.name


class debt(models.Model):
    room = models.ForeignKey(room,on_delete = models.CASCADE, related_name = 'room_debts')
    transaction = models.ForeignKey(transaction, on_delete = models.CASCADE, related_name = 'transactions_debt')
    sender = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'transaction_sender')
    receiver = models.ForeignKey(User, on_delete= models.CASCADE, related_name = 'transaction_receiver')
    amount = models.IntegerField()

    def __str__(self):
        return self.sender.username + ' pay to ' + self.receiver.username + ' in room ' + self.room.name

class final_transactions(models.Model):
    sender = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'final_transaction_sender')
    receiver = models.ForeignKey(User, on_delete= models.CASCADE, related_name = 'final_transaction_receiver')
    final_amount = models.IntegerField()

    def __str__(self):
        return self.sender.username + ' gives amount ' + str(self.final_amount) + ' to ' +self.receiver.username

class Personal_income(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    description = models.CharField(max_length = 250)
    amount = models.IntegerField()

    def __str__(self):
        return self.description

class Personal_expense(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    description = models.CharField(max_length = 250)
    amount = models.IntegerField()

    def __str__(self):
        return self.description

splitter/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from splitter.models import User,room,room_members,transaction,debt

class UserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta():
        model = User
        fields = ['username','email','password1','password2']

class RoomForm(forms.ModelForm):
    class Meta():
        model = room
        fields = ['name']

money_splitter/views.py
from django.views.generic import TemplateView

splitter/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,logout,authenticate
from django.http import HttpResponseRedirect,HttpResponse
from splitter.forms import UserForm,RoomForm
from splitter.models import User,room,room_members,transaction,debt,final_transactions,Personal_income,Personal_expense
from django.template.loader import render_to_string
from django.db.models import Q
from django.contrib import messages
import smtplib
from email.message import EmailMessage
# Create your views here.

def joinus(request):
    return render(request,'splitter/joinus.html',{})


def signup(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        if(User.objects.filter(username=username).exists()):
            messages.error(request, "Username already exists, try to signin or choose different username")
            return redirect('splitter:joinus')
        else:
            user = User.objects.create_user(username=username, password=password, email=email)
            user.save()
            messages.error(request,'Account successfully created! Try logging now')
            return HttpResponseRedirect(reverse('home'))


## Logout view
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

## Login view
def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))

            else:
                return HttpResponse("Account not active")
        else:
            messages.error(request, "Invalid Details")
            return redirect("splitter:joinus")


"""
Room creation view.
When user creates new room. A new object is created in room model with user as creater.
Also User is automatically added in the group so another object is to be created for room_members model.
"""
def add_room(request):
    if request.method == "POST":
        room_name = request.POST.get('room_name')
        new_room = room(creater=request.user,name=room_name)
        new_room.save()
        member = room_members(room=new_room,member=request.user)
        member.save()
        return HttpResponseRedirect(reverse('splitter:room_list'))
    return render(request,'splitter/room_list.html',{'form':form})


"""
Display all the rooms in which user is a member.
Filter objects from room_members model.
"""
def room_list(request):
    rooms = room_members.objects.filter(member=request.user)
    rooms_list = [x.room for x in rooms]
    length = False
    if(len(rooms_list) == 0):
        length = True
    print(len(rooms_list))
    return render(request,'splitter/room_list.html',{'rooms_list':rooms_list,'length':length})



"""
Display all the details of the room.
Room name, Creator, number of members, All the transaction made in the room.
"""
def room_details(request,pk):
    rooms = get_object_or_404(room,pk=pk)
    creator = False
    if request.user == rooms.creater:
        creator = True
    members = room_members.objects.filter(room=rooms)
    members_list = [x.member for x in members]
    members_count = len(members_list)
    transactions = transaction.objects.filter(room=rooms)
    return render(request,'splitter/room_detail.html',{'rooms':rooms,
                                                        'members_list':members_list,
                                                        'transactions':transactions,
                                                        'members_count':members_count,
                                                        'creator':creator})

## Add members in the room.
def add_member(request,pk,id):
    in_room = get_object_or_404(room,pk=pk)
    member = get_object_or_404(User,id=id)
    room_member = room_members(room=in_room,member=member)
    room_member.save()
    return HttpResponseRedirect(reverse('splitter:list_members',kwargs={'pk':pk}))

## List of all users
def list_members(request,pk):
    rooms = get_object_or_404(room,pk=pk)
    query = request.GET.get("q", None)
    members = room_members.objects.filter(room=rooms)
    members_list = [x.member for x in members]
    qs = User.objects.all()
    if query is not None:
        qs = qs.filter(
                Q(username__icontains=query)
                )
    qs_one = []
    for x in qs:
        if x in members_list:
            pass
        else:
            qs_one.append(x)

    context = {
        "members_list": qs_one,
        "rooms":rooms
    }
    template = "splitter/members_list.html"
    return render(request, template, context)




"""
transaction details view.
amount,reason,splitters and all details of transaction.
"""
def transaction_details(request,pk):
    transactions = get_object_or_404(transaction,pk=pk)
    members = room_members.objects.filter(room=transactions.room)
    all_room_members = [x.member for x in members]
    transaction_splitters = transactions.splitters.all()
    transaction_splitters_username = [x.username for x in transaction_splitters]
    return render(request,'splitter/transaction_details.html',{'transaction':transactions,'transaction_splitters_username':transaction_splitters_username,'all_room_members':all_room_members,'transaction_splitters':transaction_splitters})

# Create transaction View
# Take all the data of transaction and create transaction object. Payer will be the current user.
# Take the list of splitters and make debt object for each of them.
# For all the splitters, filter the objects in final_transactions model with user and another person.
# If there is no object created then create one else update it.
# Show the create transaction form as a pop-up form in room detail page.
def create_transaction(request,pk):
    rooms = get_object_or_404(room,pk=pk)
    if request.method == "POST":
        try:
            reason = request.POST.get('reason')
            amount = request.POST.get('amount')
            transaction_members = request.POST.getlist('splitter')
            splitters = User.objects.filter(username__in = transaction_members)
            obj = transaction(room = rooms,amount=amount,reason=reason,payer=request.user)
            obj.save()
            obj.splitters.add(*splitters)
            for x in splitters:
                if x == request.user:
                    pass
                else:
                    debt_obj = debt(room = rooms,transaction=obj,sender=x,receiver=request.user,amount=int(amount)/len(splitters))
                    debt_obj.save()
                    if_user_sender = final_transactions.objects.filter(sender=request.user,receiver=x)
                    if_user_receiver = final_transactions.objects.filter(sender=x,receiver=request.user)
                    if len(if_user_receiver) == 0 and len(if_user_sender) == 0:
                        final_obj = final_transactions(sender=x,receiver=request.user,final_amount=int(amount)/len(splitters))
                        final_obj.save()
                    else:
                        if len(if_user_receiver) == 1 and len(if_user_sender) == 0:
                            final_objs = final_transactions.objects.get(sender=x,receiver=request.user)
                            final_objs.final_amount += int(amount)/len(splitters)
                            final_objs.save()
                        else:
                            final_objs = final_transactions.objects.get(sender=request.user,receiver=x)
                            final_objs.final_amount -= int(amount)/len(splitters)
                            final_objs.save()
            return HttpResponseRedirect(reverse('splitter:room_detail',kwargs={'pk':pk}))
        except:
            messages.error(request, "Details do not match the specified data type. (Hint: amount should be integer)")
            return HttpResponseRedirect(reverse('splitter:room_detail',kwargs={'pk':pk}))
    # return render(request,'splitter/create_transaction.html',{'members':members,'rooms':rooms})



"""
Updating transaction view.
Abstract the list  of all the members of room to add them in the form for updating from room_member model.
Get the previous transaction details which is going to be updated.
Make the new transaction from data given by user in updating transaction form.
Update all the final_transactions objects between previous transaction splitters and user to delete all the debts created by that transaction.
Again update final_transactions objects according to the new data i.e. between new splitters and user with new amount(depending on the data given).
create the debt objects for Updated transaction.
Delete previous transaction.
"""
def update_transaction(request,pk,id):
    rooms = get_object_or_404(room,pk=pk)
    members_list = room_members.objects.filter(room=rooms)
    members = [x.member for x in members_list]
    prev_transaction = get_object_or_404(transaction,id=id)
    prev_amount = prev_transaction.amount
    prev_reason = prev_transaction.reason
    prev_splitters = prev_transaction.splitters.all()
    prev_splitters_usernames = [x.username for x in prev_splitters]
    if request.method == "POST":
        new_reason = request.POST.get('reason')
        new_amount = request.POST.get('amount')
        new_transaction_members = request.POST.getlist('splitter')
        new_splitters = User.objects.filter(username__in = new_transaction_members)
        obj = transaction(room = rooms,amount=new_amount,reason=new_reason,payer=request.user)
        obj.save()
        obj.splitters.add(*new_splitters)
        for x in prev_splitters:

templates/splitter/delete_debt.html
{% extends 'splitter/base.html' %}
{% block content %}

<div class="container">
  <div class="jumbotron">
    <h4>Are you sure you want to settle the debt?</h4>
    <form method="post">
      {% csrf_token %}
      <input type="submit" value="Yes" class="btn btn-primary" >
      <a href="{% url 'splitter:my_debts' %}" class="btn btn-danger">Cancel</a>
    </form>
  </div>
</div>

{% endblock %}

templates/splitter/delete_personal_budget.html
{% extends 'splitter/base.html' %}
{% block content %}

<div class="container">
  <div class="jumbotron">
    <h4>Are you sure you want to delete {{ obj.description }}?</h4>
    <form method="post">
      {% csrf_token %}
      <input type="submit" value="Yes" class="btn btn-primary" >
      <a href="{% url 'splitter:personal_budget' %}" class="btn btn-danger">Cancel</a>
    </form>
  </div>
</div>


{% endblock %}

templates/splitter/joinus.html
{% extends 'splitter/base.html' %}
{% load static %}
{% load socialaccount %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/login_signup.css' %}">
{% endblock %}
{% block content %}

{% if messages %}
<div class="container">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      {% for message in messages %}
        <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
      {% endfor %}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
</div>
{% endif %}

<div class="containers">
    <div class="forms-containers">
        <div class="signin-signup">
            <form class="sign-in-form" action="{% url 'splitter:login' %}" method="post">
                <h2 class="title">Sign In</h2>
                <div class="input-field">
                    <i class="fas fa-user"></i>
                    <input type="text" name="username" placeholder="Username" />
                </div>
                <div class="input-field">
                    <i class="fas fa-lock"></i>
                    <input type="password" name="password" placeholder="Password" />
                </div>
                <input type="submit" value="Login" class="btn solid" />
                <p class="social-text">Or Sign in with social platform</p>
                <div class="social-media">
                    <a href="{% provider_login_url 'google' %}" class="social-icon"><i class="fab fa-google"></i></a>
                </div>
            </form>
            <form class="sign-up-form" action="{% url 'splitter:signup' %}" method="POST">
                <h2 class="title">Sign Up</h2>
                <div class="input-field">
                    <i class="fas fa-user"></i>
                    <input type="text" name="username" placeholder="Username" />
                </div>
                <div class="input-field">
                    <i class="fas fa-envelope"></i>
                    <input type="email" name="email" placeholder="Email" />
                </div>
                <div class="input-field">
                    <i class="fas fa-lock"></i>
                    <input type="password" name="password" placeholder="Password" />
                </div>
                <input type="submit" value="Sign Up" class="btn solid" />
                <p class="social-text">Or Sign up with social platform</p>
                <div class="social-media">
                  <a href="{% provider_login_url 'google' %}" class="social-icon"><i class="fab fa-google"></i></a>
                </div>
            </form>
        </div>
    </div>
    <div class="panels-containers"  >
        <div class="panel left-panel" >
            <div class="content">
                <h3>New Here ?</h3>
                <p>Dont have an account on our website and want to enjoy the great time saving features, just click on the button below to signup</p>
                <button class="btn transparent" id="sign-up-btn">Sign Up</button>
            </div>
            <img src="{% static 'images/login1.svg' %}" class="image" alt="">
        </div>
        <div class="panel right-panel">
            <div class="content">
                <h3>One of Us ?</h3>
                <p>Already have an account, just click on the login button.</p>
                <button class="btn transparent" id="sign-in-btn">Sign In</button>
            </div>
            <img src="{% static 'images/login2.svg' %}" class="image" alt="">
          </div>
      </div>
 </div>


<script src="{% static 'js/app.js' %}">

</script>


{% endblock %}

templates/splitter/my_debts.html
{% extends 'splitter/base.html' %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/mysearchbar.css' %}">
  <link rel="stylesheet" href="{% static 'css/my_debts.css' %}">
{% endblock %}
{% block content %}

<div class="container">
    {% for message in messages %}

      <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
    {% endfor %}
    
  
  <div class="my-debts-info">
    <form method='GET' action="{% url 'splitter:my_debts' %}">
      <p>Search User: <input type='search' name='q' placeholder='Search'></p>
    </form>
    <div class="my-debts-income">
      <h1>Payments to receive:</h1>
      <div class="row">
         {% if incomes.count == 0 %}
         <h4>No payments to receive!!!</h4>
         {% else %}
        {% for income in incomes %}
        <div class="col-lg-3 col-md-4 col-sm-6 col-12">
          <div class="my-debts-income-info">
            <h4>{{ income.amount }}</h4>
            <p>From {{ income.sender.username }}</p>
            <p>For {{ income.transaction.reason }}</p>
            <p>Room {{ income.room.name }}</p>
            <p>{{ income.transaction.created_at }}</p>
            <a href="{% url 'splitter:delete_debt' pk=income.pk %}" data-target="#{{ income.sender.username }}_{{ income.pk }}" data-toggle="modal">
              <div class="settle-debt-button">
                
                  Settle Debt
                  
              </div>
            </a>
            <a href = "{% url 'splitter:remainder' income.sender.username income.amount %}">
              <div class="btn btn-primary">Reminder</div>
            </a>
          </div>
        </div>
        <div class="modal fade" tabindex="-1" role="dialog" id="{{ income.sender.username }}_{{ income.pk }}" data-backdrop="static" data-keyboard="false" aria-labelledby="staticBackdropLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Settle Debt of {{ income.sender.username }} for {{ income.transaction.reason }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form action="{% url 'splitter:delete_debt' pk=income.pk %}" method="post">
                  {% csrf_token %}
                  <input type="submit" value="Yes" class="btn btn-primary">
                </form>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        {% endif %}
      </div>
    </div>
    <div class="my-debts-expense">
      <h1>Amounts to pay:</h1>
    {% comment %} <p><a href="{% url 'splitter:payment' %}">Pay Now</a></p>   {% endcomment %}
      <div class="row">
        {% if expenses.count == 0 %}
        <h4>No amounts to pay!!!</h4>
        {% else %}
        {% for expense in expenses %}
        <div class="col-lg-3 col-md-4 col-sm-6 col-12">
          <div class="my-debts-expense-info">
            <h4>{{ expense.amount }}</h4>
            <p>Give to {{ expense.receiver.username }}</p>
            <p>For {{ expense.transaction.reason }}</p>
            <p>Room {{ expense.room.name }}</p>
            <p>{{ expense.transaction.created_at }}</p>
            {% comment %} <div id="paypal-button-container"></div>
            <script src="https://www.paypal.com/sdk/js?client-id=AVJkK17e_zC6ImpVSnqsweVOMkwCuh-kQvyJA2ZS6TcaySPpg1ueVpc_z_8ksL0lPR8ZxF118-d_0dAR&currency=USD"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: {{ expense.amount }}
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(orderData) {
                    // Successful capture! For demo purposes:
                    console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                    var transaction = orderData.purchase_units[0].payments.captures[0];
                    alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');
                    expense.amount=0;
                          
                    // Replace the above to show a success message within this page, e.g.
                    // const element = document.getElementById('paypal-button-container');
                    // element.innerHTML = '';
                    // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                    // Or go to another URL:  actions.redirect('thank_you.html');
                });
            }
          



        }).render('#paypal-button-container');
    </script> {% endcomment %}
          </div>
        </div>
        {% endfor %}
        {% endif %}
      </div>
    </div>
    <a href="{% url 'splitter:final_settlements' %}" class="btn btn-primary final-debts-button">Show Final Debts</a>
  </div>
  </div>

{% endblock %}

templates/splitter/personal_budget.html
{% extends 'splitter/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/personal_budget.css' %}">
{% endblock %}
{% block content %}

{% if messages %}
<div class="container">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      {% for message in messages %}
        <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
      {% endfor %}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
</div>
{% endif %}
<div class="budget-top">
  <img class="budget-top-background" src="{% static 'images/personal_budget_background.PNG' %}">
  <div class="show-budget">
    <h1>Final Budget</h1>
    <h2>{{ total_bud }}</h2>
    <div class="income-box">
      <p>Total Income</p>
      <p>{{ total_income }}</p>
    </div>
    <div class="expense-box">
      <p>Total Expense</p>
      <p>{{ total_expenses }}</p>
    </div>
  </div>
</div>

<div class="budget-form">
  <form action="{% url 'splitter:add_personal_budget' %}" method="post">
    {% csrf_token %}
    <select id="type" name="type" class="form-inputs">
        <option value="inc">+</option>
        <option value="exp">-</option>
    </select>
    <input type="text" name="description" placeholder="Description" class="form-inputs">
    <input type="text" name="amount" placeholder="Amount" class="form-inputs">
    <input type="submit" class="form-inputs btn btn-primary">
  </form>
</div>


<div class="budget-bottom">
  <div class="row">
      <div class="col-md-6 col-sm-12">
        <h2>Income</h2>
        <div class="budget-info-list income">
          {% for income in incomes %}
          <div class="item clearfix">
            <div class="item__description">{{ income.description }}</div>
              <div class="right clearfix">
                  <div class="item__value">{{ income.amount }}</div>
                  <a href="" data-target="#id_{{ income.pk }}" data-toggle="modal">
                  <div class="item__delete">
                      <button class="item__delete--btn"><i class="fal fa-times-circle"></i></button>
                  </div>
                  </a>
              </div>

         <div class="modal fade" tabindex="-1" role="dialog" id="id_{{ income.pk }}" data-backdrop="static" data-keyboard="false" aria-labelledby="staticBackdropLabel" aria-hidden="true">
           <div class="modal-dialog modal-dialog-centered">
             <div class="modal-content">
               <div class="modal-header">
                 <h5 class="modal-title">Delete {{ income.description }} Income</h5>
                 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                   <span aria-hidden="true">&times;</span>
                 </button>
               </div>
               <div class="modal-body">
                 <form action="{% url 'splitter:delete_personal_income' pk=income.pk %}" method="post">
                   {% csrf_token %}
                   <input type="submit" value="Yes" class="btn btn-primary">
                 </form>
               </div>
             </div>
           </div>
         </div>
         </div>
          {% endfor %}
        </div>
      </div>
      <div class="col-md-6 col-sm-12">
        <h2>Expense</h2>
        <div class="budget-info-list expenses">
          {% for expense in expenses %}
          <div class="item clearfix">
            <div class="item__description">{{ expense.description }}</div>
              <div class="right clearfix">
                  <div class="item__value">{{ expense.amount }}</div>
                  <a href="" data-target="#id_{{ expense.pk }}" data-toggle="modal">
                  <div class="item__delete">
                      <button class="item__delete--btn"><i class="fal fa-times-circle"></i></button>
                  </div>
                  </a>
              </div>

         <div class="modal fade" tabindex="-1" role="dialog" id="id_{{ expense.pk }}" data-backdrop="static" data-keyboard="false" aria-labelledby="staticBackdropLabel" aria-hidden="true">
           <div class="modal-dialog modal-dialog-centered">
             <div class="modal-content">
               <div class="modal-header">
                 <h5 class="modal-title">Delete {{ expense.description }} Expense</h5>
                 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                   <span aria-hidden="true">&times;</span>
                 </button>
               </div>
               <div class="modal-body">
                 <form action="{% url 'splitter:delete_personal_expense' pk=expense.pk %}" method="post">
                   {% csrf_token %}
                   <input type="submit" value="Yes" class="btn btn-primary">
                 </form>
               </div>
             </div>
           </div>
         </div>
        </div>
          {% endfor %}
        </div>
      </div>
  </div>
</div>
{% endblock %}

templates/splitter/update_transaction.html
{% extends 'splitter/base.html' %}
{% block content %}

<div class="container">
    <div class="jumbotron">
        <form action="{% url 'splitter:update_transaction' pk=rooms.pk id=prev_transaction.id %}" method="post">
          {% csrf_token %}
          <input type="text" name="reason" value='{{ prev_transaction.reason }}'>
          <input type="number" name="amount" value='{{ prev_transaction.amount }}'>
          {% for member in members %}
          <input type="checkbox" name="splitter" value='{{ member.username }}' {% if member.username in prev_splitters_usernames %} checked="checked" {% endif %}>{{ member.username }}<br>
          {% endfor %}
          <input type="submit" class="btn btn-primary" name="" value="Submit">
        </form>
    </div>
</div>

{% endblock %}